### PR TITLE
Create Tonkeeper Hindi translation

### PR DESCRIPTION
**Pull request by Abdulll0**
hi.json

### CODE REVIEW

**Comment by Abdulll0** [comment]
@KuznetsovNikita 
This is the last one.
Tonkeeper Hindi translation

**Comment by KuznetsovNikita** [comment]
Hello @Abdulll0 
Thank you for contribution!
Please direct message to https://t.me/nKuznetsov5
To be invited to Tonkeeper Group!

**Review by KuznetsovNikita — APPROVED** [review]

**Comment by Abdulll0** [comment]
> Hello @Abdulll0 Thank you for contribution! Please direct message to https://t.me/nKuznetsov5 To be invited to Tonkeeper Group!

please i cant be able to message you first
i will be glad if you message me first
this is my telegram link
t.me/Abdulqudus0001

**Comment by Abdulll0** [comment]
> > Hello @Abdulll0 Thank you for contribution! Please direct message to https://t.me/nKuznetsov5 To be invited to Tonkeeper Group!
> 
> please i cant be able to message you first i will be glad if you message me first this is my telegram link t.me/Abdulqudus0001

t.me/Abdulqudus0001

**Comment by Abdulll0** [comment]
> > Hello @Abdulll0 Thank you for contribution! Please direct message to https://t.me/nKuznetsov5 To be invited to Tonkeeper Group!
> 
> please i cant be able to message you first i will be glad if you message me first this is my telegram link t.me/Abdulqudus0001

hh

> > Hello @Abdulll0 Thank you for contribution! Please direct message to https://t.me/nKuznetsov5 To be invited to Tonkeeper Group!
> 
> please i cant be able to message you first i will be glad if you message me first this is my telegram link t.me/Abdulqudus0001

https://t.me/Abdulqudus0001

**Comment by Abdulll0** [comment]
> > > Hello @Abdulll0 Thank you for contribution! Please direct message to https://t.me/nKuznetsov5 To be invited to Tonkeeper Group!
> > 
> > 
> > please i cant be able to message you first i will be glad if you message me first this is my telegram link t.me/Abdulqudus0001
> 
> hh
> 
> > > Hello @Abdulll0 Thank you for contribution! Please direct message to https://t.me/nKuznetsov5 To be invited to Tonkeeper Group!
> > 
> > 
> > please i cant be able to message you first i will be glad if you message me first this is my telegram link t.me/Abdulqudus0001
> 
> https://t.me/Abdulqudus0001

@KuznetsovNikita

**Pull request merged**
