### PR TITLE
add Farsi (fa) locale for tonkeeper-web

### PR DESCRIPTION
**Pull request by saraeygh**
Added Farsi (fa.json) locale for "tonkeeper-web" folder.

### CODE REVIEW

**Comment by saraeygh** [comment]
hi, why PR closed? whats the problem? is there any problem related to changes or  PR?

**Comment by KuznetsovNikita** [comment]
@saraeygh hello
As I got it, you created your PR base of my working branch, and GitHub it automatically close after branch was deleted

Please recreate it base “main”

**Comment by KuznetsovNikita** [comment]
I changed base to "main"

**Comment by saraeygh** [comment]
@KuznetsovNikita 
Hi, I checked out my branch from your working branch "feature/locales". Is it ok or I should create my branch out of "main" branch?

**Review by KuznetsovNikita — APPROVED** [review]

**Pull request merged**
